# CircleCI config
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15
    working_directory: ~/ec-commitments
    steps:
      - checkout
      - run: npm install
      - run: npm test
